### ISSUE TITLE
Can't put spiceDL.js into config-xpui.ini and start python daemon.

### ISSUE THREAD

**Issue by quackgoestheduck** [FoxRefire/spiceDL#3]
A more detailed, step by step guide would be very much appreciated.

Thanks in advance.

**Comment by FoxRefire** [comment]
1 Place spiceDL.js into directory that correspond for your OS.
| Platform | Path |
|--------| --------|
| Windows | %appdata%\spicetify\Extensions\ | 
| Linux/MacOS | ~/.config/spicetify/Extensions | 

2 run :
```
spicetify config extensions spiceDL.js
spicetify apply
```

3 start daemon
```
pip3 install flask flask_cors # Install dependencies
python3 serve.py
```

**Comment by FoxRefire** [comment]
Ah, it already published at market place.
so, step 1 and step 2 is not needed. just install from marketplace.
and then start python daemon.

**Comment by ilysnemo** [comment]
I dont see SpiceDL in marketplace, am i miss something?
